name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {} # reset

jobs:
  release:
    name: Release
    # IMPORTANT: prevent this action from running on forks
    if: github.repository == 'fellipeutaka/ayanokoji'
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
      id-token: write # Required for OIDC trusted publishing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # This is necessary since Bun doesn't support OIDC yet. See https://github.com/oven-sh/bun/issues/22423
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build the CLI
        run: bun run build

      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          publish: "npx changeset publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
