name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {} # reset

jobs:
  release:
    name: Release
    # IMPORTANT: prevent this action from running on forks
    if: github.repository == 'fellipeutaka/ayanokoji'
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
      id-token: write # Required for OIDC trusted publishing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          publish: pnpm run release
